// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTKLjbSeWiQ5PKlQjjYJBYDQtc46G7SVE',
    appId: '1:499058000442:web:01aee4f2c7840c24e7ab03',
    messagingSenderId: '499058000442',
    projectId: 'chat-app-a81f2',
    authDomain: 'chat-app-a81f2.firebaseapp.com',
    storageBucket: 'chat-app-a81f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0F66b26F7A-XNVJwY_Zc0EpWNiqDaQrQ',
    appId: '1:499058000442:android:7fbcd7210baea725e7ab03',
    messagingSenderId: '499058000442',
    projectId: 'chat-app-a81f2',
    storageBucket: 'chat-app-a81f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqQ9TkA_lmmfyzX7VE5L_TCjPGgbFNhfE',
    appId: '1:499058000442:ios:3466f27d157d419fe7ab03',
    messagingSenderId: '499058000442',
    projectId: 'chat-app-a81f2',
    storageBucket: 'chat-app-a81f2.appspot.com',
    iosBundleId: 'com.example.rentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqQ9TkA_lmmfyzX7VE5L_TCjPGgbFNhfE',
    appId: '1:499058000442:ios:3466f27d157d419fe7ab03',
    messagingSenderId: '499058000442',
    projectId: 'chat-app-a81f2',
    storageBucket: 'chat-app-a81f2.appspot.com',
    iosBundleId: 'com.example.rentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTKLjbSeWiQ5PKlQjjYJBYDQtc46G7SVE',
    appId: '1:499058000442:web:e5c1ab2d9756868ee7ab03',
    messagingSenderId: '499058000442',
    projectId: 'chat-app-a81f2',
    authDomain: 'chat-app-a81f2.firebaseapp.com',
    storageBucket: 'chat-app-a81f2.appspot.com',
  );
}
