import 'hotel_model.dart';

final List<HotelModel> dummyHotels = [
  HotelModel(
    uid: '1',
    name: "Seaside Bliss Resort",
    location: "Goa",
    price: 4200,
    rating: 4.8,
    images: [
      "https://images.oyoroomscdn.com/uploads/hotel_image/9497/large/bulebaxppqxh.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/9497/large/hascpjowtwqb.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/173030/large/ucjdtotjhtdd.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/9497/large/ktimtmigekdr.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/9497/large/yryajlioshtn.jpg",
    ],
    description: "Escape to serenity with this oceanfront luxury resort.",
    hostName: "Ravi Kumar",
    hostProfileImage: "https://randomuser.me/api/portraits/men/32.jpg",
    hostPhone: "+91 9876543210",
    hostEmail: "ravi@seasidebliss.com",
    type: "Villa",
    tags: ["Sea View", "Family Friendly", "Free Breakfast"],
    amenities: ["WiFi", "AC", "Parking", "Pool", "Spa", "TV"],
    checkInTime: "1:00 PM",
    checkOutTime: "11:00 AM",
    cancellationPolicy: "Free cancellation up to 48 hours before check-in.",
    houseRules: ["No smoking", "Pets allowed", "Quiet hours after 10 PM"],
    otherInfo: ["Valid government ID required at check-in."],
    latitude: 15.2993,
    longitude: 74.1240,
    available: true,
    reviewCount: 134,
    featured: true,
  ),
  HotelModel(
    uid: '2',
    name: "Hilltop Paradise Resort",
    location: "Munnar",
    price: 3500,
    rating: 4.7,
    images: [
      "https://imgak.mmtcdn.com/pwa_v3/pwa_hotel_assets/bgdefault_bg.jpg",
      "https://r1imghtlak.mmtcdn.com/305aaa15-84b7-413a-8429-fb789b236563.jpg",
      "https://r1imghtlak.mmtcdn.com/305aaa15-84b7-413a-8429-fb789b236563.jpg",
      "https://r1imghtlak.mmtcdn.com/305aaa15-84b7-413a-8429-fb789b236563.jpg",
      "https://r1imghtlak.mmtcdn.com/305aaa15-84b7-413a-8429-fb789b236563.jpg",
    ],
    description: "Luxury retreat surrounded by hills and greenery.",
    hostName: "Anjali Nair",
    hostProfileImage: "https://randomuser.me/api/portraits/women/44.jpg",
    hostPhone: "+91 9012345678",
    hostEmail: "anjali@hilltopresort.com",
    type: "Deluxe",
    tags: ["Mountain View", "Couple Friendly"],
    amenities: ["WiFi", "TV", "Breakfast", "Hot Water", "Parking"],
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    cancellationPolicy: "Non-refundable within 24 hours.",
    houseRules: ["No pets", "No outside food"],
    otherInfo: ["Children under 5 stay free."],
    latitude: 10.0889,
    longitude: 77.0595,
    available: true,
    reviewCount: 98,
    featured: false,
  ),
  HotelModel(
    uid: '3',
    name: "City View Inn",
    location: "Delhi",
    price: 1800,
    rating: 4.2,
    images: [
      "https://r1imghtlak.mmtcdn.com/e1c00f2e-672c-47d9-b28b-bf33f2119236.jpeg",
      "https://r1imghtlak.mmtcdn.com/f0477136-2480-4d9c-816c-0c112c2f0db7.jpeg",
      "https://r1imghtlak.mmtcdn.com/56edad53-232f-4368-b25d-e6b6bdfd8f5f.jpeg",
      "https://r1imghtlak.mmtcdn.com/ae6b0265-5c96-406d-908b-fa8ebd1ee43f.jpeg",
      "https://r1imghtlak.mmtcdn.com/1218ec7b-7e58-44bb-904b-67f57df2753f.jpeg",
    ],
    description: "Comfortable stay in the heart of the city.",
    hostName: "Deepak Sharma",
    hostProfileImage: "https://randomuser.me/api/portraits/men/85.jpg",
    hostPhone: "+91 9991122334",
    hostEmail: "deepak@cityview.com",
    type: "Standard",
    tags: ["Near Metro", "Budget Friendly"],
    amenities: ["WiFi", "AC", "TV", "Parking"],
    checkInTime: "2:00 PM",
    checkOutTime: "12:00 PM",
    cancellationPolicy: "Free cancellation up to 24 hours.",
    houseRules: ["No loud music", "ID required"],
    otherInfo: ["Staff available 24/7."],
    latitude: 28.6139,
    longitude: 77.2090,
    available: true,
    reviewCount: 45,
    featured: false,
  ),
  HotelModel(
    uid: '4',
    name: "Ginger Goa, Candolim",
    location: "Goa",
    price: 1800,
    rating: 4.5,
    images: [
      "https://r1imghtlak.mmtcdn.com/0f00d12b-9701-420b-b944-7cf35bc4d064.jpg",
      "https://r2imghtlak.mmtcdn.com/r2-mmt-htl-image/htl-imgs/202410211734063978-3075721f-29bd-42d6-ae75-ac8bfb9fea77.jpg",
      "https://r2imghtlak.mmtcdn.com/r2-mmt-htl-image/htl-imgs/202410211734063978-37391430-37af-4446-bf6d-f66644666541.jpg",
      "https://r1imghtlak.mmtcdn.com/48c960bf-fcfe-414f-b2b9-9ae0a2210ff6.jpg",
      "https://r1imghtlak.mmtcdn.com/785806fd-fb01-4955-a1dd-f2c71d731cca.jpeg",
    ],
    description:
        "way from the pristine Candolim Beach. The hotel offers well-appointed rooms, contemporary amenities, and a warm, welcoming ambiance, making it ideal for both leisure and business travelers. Guests can enjoy delicious dining options, a well-equipped fitness center, and seamless connectivity. With its strategic location near popular tourist spots, Ginger Hotel Candolim provides easy access to Goa's rich cultural and natural attractions. It’s the perfect blend of comfort, convenience, and affordability for a memorable stay..",
    hostName: "Darrell Sims",
    hostProfileImage: "https://randomuser.me/api/portraits/men/5.jpg",
    hostPhone: "+91 9591122334",
    hostEmail: "Darrell@ginger.com",
    type: "delux",
    tags: ["Near Metro", "Budget Friendly"],
    amenities: ["WiFi", "AC", "TV", "Parking"],
    checkInTime: "2:00 PM",
    checkOutTime: "12:00 PM",
    cancellationPolicy: "Free cancellation up to 24 hours.",
    houseRules: ["No loud music", "ID required", "Pets are not allowed"],
    otherInfo: ["Staff available 24/7."],
    latitude: 28.6139,
    longitude: 77.2090,
    available: true,
    reviewCount: 45,
    featured: true,
  ),
];
